name: Daily Countdown Update
on:
  schedule:
    - cron: '*/10 * * * *'  # Test: Runs every 10 minutes
  workflow_dispatch:
jobs:
  send-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install python-telegram-bot pytz
      - name: Run Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python bot.py
