name: Daily Telegram Countdown

on:
  schedule:
    # Mar–Oct (CEST, UTC+2): 18:30 CH = 16:30 UTC
    - cron: '00 7 * 3-10 *'
    # Nov–Feb (CET, UTC+1): 18:30 CH = 17:30 UTC
    - cron: '00 8 * 11,12,1,2 *'
  workflow_dispatch:

jobs:
  send-countdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Telegram bot script
        env:
          POSITIVE_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}  # or change your code to read BOT_TOKEN
          # If your countdown bot needs group IDs as a secret:
          # GROUP_IDS: ${{ secrets.GROUP_IDS }}
        run: countdown.py
