name: Daily Telegram Australia Countdown

on:
  schedule:
    # Mar–Oct (CEST = UTC+2): 09:00 CH = 07:00 UTC
    - cron: '0 7 * 3-10 *'
    # Nov–Feb (CET = UTC+1): 09:00 CH = 08:00 UTC
    - cron: '0 8 * 11,12,1,2 *'
  workflow_dispatch:

jobs:
  send-countdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Telegram bot script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python bot.py
