name: Daily Countdown Update

concurrency: 
  group: countdown-bot
  cancel-in-progress: true


on:
  schedule:
  - cron: '0 16 * * *'  # 18:00 CEST (summer)
  - cron: '0 17 * * *'  # 18:00 CET (winter)
workflow_dispatch:

jobs:
  send-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install python-telegram-bot pytz
      - name: Run Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python bot.py
