name: Daily Countdown Update

concurrency: 
  group: countdown-bot
  cancel-in-progress: true


on:
  schedule:
    - cron: '0 17 * * *'  # 17:00 UTC = 18:00 CET (UTC+1)
  workflow_dispatch:       # Allows manual triggers

jobs:
  send-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install python-telegram-bot pytz
      - name: Run Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python bot.py
